apiVersion: v1
kind: Namespace
metadata:
  name: "smb-policies"
  labels:
    name: "smb-policies"
---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "smb-common-policy"
  namespace: "smb-policies"
spec:
  bindingRules:
    siteName: "smb-common-policy"
    common: "true"
